squirrels/sightings/urls.py
from  django.urls import path
from . import views
app_name = 'sightings'
urlpatterns = [
        path('add', views.add, name='add'),
        path('stats', views.stats, name='stats'),
        path('', views.sightings, name='sightings'),
        path('<str:unique_squirrel_id>', views.update, name='update'),
        path('<str:unique_squirrel_id>/delete', views.delete, name='delete'),
        ]

squirrels/squirrels/urls.py
from django.contrib import admin
from django.urls import include, path
from sightings.views import map_
urlpatterns = [
        path('sightings/', include('sightings.urls')),
        path('map/', map_),
        path('admin/', admin.site.urls),
]

squirrels/sightings/models.py
from django.db import models
from django.utils.translation import gettext as _

class Sighting(models.Model):
    X = models.DecimalField(help_text=_('Longitude'), max_digits=50, decimal_places=20)
    Y = models.DecimalField(help_text=_('Latitude'), max_digits=50, decimal_places=20)
    unique_squirrel_id = models.CharField(help_text=_('unique squirrel id'), max_length=100, primary_key=True)
    
    AM = 'AM'
    PM = 'PM'
    
    SHIFT = (
            (AM,'AM'),
            (PM,'PM'),
            )
    
    Shift = models.CharField(help_text=_('Shift'), max_length=10, choices=SHIFT)
    
    Date = models.DateField(help_text=_('Date'),)
    
    Adult = 'Adult'
    Juvenile = 'Juvenile'
    Nil = ''
    Unknown = 'Unknown'
    
    AGE = (
          (Adult,'Adult'),
          (Juvenile,'Juvenile'),
          (Nil,''),
          (Unknown,'?'),
          )
    
    Age = models.CharField(help_text=_('Age'), max_length=50, choices=AGE, blank=True)
    
    Gray = 'Gray'
    Black = 'Black'
    Cinnamon = 'Cinnamon'
    Nil = ''
    
    Primary_Fur_Color = (
                         (Gray, 'Gray'),
                         (Black, 'Black'),
                         (Cinnamon, 'Cinnamon'),
                         (Nil, ''),
                         )
    
    Primary_Fur_Color = models.CharField(help_text=_('Primary Fur Color'), max_length=20, choices = Primary_Fur_Color, blank=True)
    
    Ground_Plane = 'Ground Plane'
    Above_Ground = 'Above Ground'
    Nil = ''
    
    LOCATION = (
               (Ground_Plane, 'Ground Plane'),
               (Above_Ground, 'Above Ground'),
               (Nil, ''),
               )
    
    Location = models.CharField(help_text=_('Location'), max_length=100, choices = LOCATION, blank=True)
    Specific_Location = models.CharField(help_text=_('Specific Location'), max_length=100, blank=True)
    TRUE = 'True'
    FALSE = 'False'

    True_False = (
                 (TRUE, 'True'),
                 (FALSE, 'False')
                 )
    
    Running = models.CharField(help_text=_('Running'), max_length=10, choices=True_False)
    Chasing = models.CharField(help_text=_('Chasing'), max_length=10, choices=True_False)
    Climbing = models.CharField(help_text=_('Climbing'), max_length=10, choices=True_False)
    Eating = models.CharField(help_text=_('Eating'), max_length=10, choices=True_False)
    Foraging = models.CharField(help_text=_('Foraging'), max_length=10, choices=True_False)
    Other_Activities = models.CharField(help_text=_('Other Activities'), max_length=100, blank=True)
    Kuks = models.CharField(help_text=_('Kuks'), max_length=10, choices=True_False)
    Quaas = models.CharField(help_text=_('Quaas'), max_length=10, choices=True_False)
    Moans = models.CharField(help_text=_('Moans'), max_length=10, choices=True_False)
    Tail_Flags = models.CharField(help_text=_('Tail Flags'), max_length=10, choices=True_False)
    Tail_Twitches = models.CharField(help_text=_('Tail Twitches'), max_length=10, choices=True_False)
    Approaches = models.CharField(help_text=_('Approaches'), max_length=10, choices=True_False)
    Indifferent = models.CharField(help_text=_('Indifferent'), max_length=10, choices=True_False)
    Runs_From = models.CharField(help_text=_('Runs From'), max_length=10, choices=True_False)
    
    def __str__(self):
        return self.unique_squirrel_id

squirrels/sightings/forms.py
from django.forms import ModelForm
from sightings.models import Sighting

# Create the form class
class SightingForm(ModelForm):
    class Meta:
        model = Sighting
        fields = '__all__'
        #fields = ['X', 'Y', 'unique_squirrel_id', 'Shift', 'Date', 'Age', 'Primary_Fur_Color', 'Location', 'Specific_Location', 'Running', 'Chasing', 'Climbing', 'Eating', 'Foraging', 'Other_Activities', 'Kuks', 'Quaas', 'Moans', 'Tail_Flags', 'Tail_Twitches', 'Approaches', 'Indifferent', 'Runs_From']

squirrels/sightings/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from sightings.forms import SightingForm
from django.shortcuts import redirect
from .models import Sighting
from django.template import loader
from django.contrib import messages
from collections import Counter

def add(request):
    form_class = SightingForm
    form = form_class(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save()
            post.save()
            return redirect(f'/sightings')
    else:
         form = SightingForm()
    
    return render(request, 'sightings/add.html', {'form': form})

def sightings(request):
    all_sightings = Sighting.objects.all()[::-1]
    
    return render(request, 'sightings/sightings.html', {'all_sightings': all_sightings})

def update(request, unique_squirrel_id):
    squirrel_instance = get_object_or_404(Sighting, unique_squirrel_id=unique_squirrel_id)
    if request.method == 'POST':
        form = SightingForm(request.POST or None, instance=squirrel_instance)
        if form.is_valid():
            squirrel_instance.save()
            form.save()
            return redirect(f'/sightings')
        else:
            return HttpResponseRedirect(reverse('sightings:sightings'))
    else:
        form = SightingForm(instance=squirrel_instance)
    
    context = {'form': form, 'squirrel_instance': squirrel_instance,}
    
    return render(request, 'sightings/update.html', context)

def stats(request):
    all_sightings = Sighting.objects.all()
    all_sightings_PM = Sighting.objects.filter(Shift='PM').count()
    all_sightings_AM = Sighting.objects.filter(Shift='AM').count()
    all_sightings_grey = Sighting.objects.filter(Primary_Fur_Color='Gray').count()
    all_sightings_cinnamon = Sighting.objects.filter(Primary_Fur_Color='Cinnamon').count()
    all_sightings_black = Sighting.objects.filter(Primary_Fur_Color='Black').count()
    all_sightings_running = Sighting.objects.filter(Running='true').count()
    all_sightings_ground_plane = Sighting.objects.filter(Location='Ground Plane').count()
    all_sightings_above_ground = Sighting.objects.filter(Location='Above Ground').count()
    all_sightings_adult = Sighting.objects.filter(Age='Adult').count()
    all_sightings_juvenile = Sighting.objects.filter(Age='Juvenile').count()

    context = {'all_sightings_PM': all_sightings_PM,
               'all_sightings_AM': all_sightings_AM,
               'all_sightings': all_sightings,
               'all_sightings_grey': all_sightings_grey,
               'all_sightings_cinnamon': all_sightings_cinnamon,
               'all_sightings_black': all_sightings_black,
               'all_sightings_running': all_sightings_running,
               'all_sightings_ground_plane': all_sightings_ground_plane,
               'all_sightings_above_ground': all_sightings_above_ground,
               'all_sightings_adult': all_sightings_adult,
               'all_sightings_juvenile': all_sightings_juvenile,
               }
    
    return render(request, 'sightings/stats.html', context)

def delete(request, unique_squirrel_id):
    squirrel_instance = get_object_or_404(Sighting, unique_squirrel_id=unique_squirrel_id)
    if request.method == "POST":
        squirrel_instance.delete()
        messages.success(request, "Sighting successfully deleted!")
        return HttpResponseRedirect('sightings')
    
    context = {'squirrel_instance': squirrel_instance,}
    
    return render(request, 'sightings/delete.html', context)

def map_(request):
    all_sightings = Sighting.objects.all()[:100]
    
    return render(request, 'sightings/map.html', {'all_sightings': all_sightings})

squirrels/sightings/templates/sightings/add.html
<html>
<p class="sightings-box">
<a href="{% url 'sightings:sightings' %}" class="sightings-link">Back to main page</a>
</p>

<div class=”page-header”>
<h1>Add a new sighting! </h1>
</div>

<div class=”content container”>
<form action="add" method="POST">
{% csrf_token %}
<table>
  {{ form.as_table }}
  </table>
  <button type="submit" class = "save btn btn-default">Post!</button>
</form>
</div>
</html>

squirrels/sightings/templates/sightings/delete.html
<!doctype html>
<html>
	<body>
<p class="sightings-box">
<a href="{% url 'sightings:sightings' %}" class="sightings-link">Back to main page</a>
</p>

<div class="page-header">
<h1>Delete a Sighting</h1>
</br>
</br>
<h2>Squirrel ID: {{squirrel_instance.unique_squirrel_id}}</h2>
</div>

<form method="post" action="">
	{% csrf_token %}
	Do you really want to delete "{{squirrel_instance.unique_squirrel.id}}"?
	<input type="submit" value="Yes, delete" />
	<a href = "{% url 'sightings:sightings' %}">{{ Cancel }}</a>
</form>
	</body>
</html>

squirrels/sightings/templates/sightings/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);
        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->
        {% for sighting in all_sightings %}
          var point_lat_lon = [{{ sighting.Y }}, {{ sighting.X }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

squirrels/sightings/templates/sightings/sightings.html
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Sightings</title>
</head>
<body>

	<a href = "add">Add A Sighting</a>
	</br>
	</br>
	<a href = "stats">Sighting Statistics</a>	
<h1>List of Sightings</h1>
<h2>Click on Squirrel ID to edit sighting</h2>
<table border="1" width="600">
<tr>
<td>Squirrel ID</td>
<td>Date</td>
<td>Shift</td>
</tr>

{% for squirrel in all_sightings %}
<tr>
<td><a href = "{% url 'sightings:update' squirrel.unique_squirrel_id %}">{{ squirrel.unique_squirrel_id }}</a></td>
<td>{{ squirrel.Date }}</td>
<td>{{ squirrel.Shift }}</td>
</tr>
{% endfor %}
</table>


</body>
</html>

squirrels/sightings/templates/sightings/stats.html
<!DOCTYPE html>
<html>
<style>
table {
	border-collapse: collapse;
}
table, th, td {
	border: 1px solid black;
	padding: 15px;
	text-align: center;
}
tr:hover {background-colour: #f5f5f5;
}
th {
	background-color: 2d2987
	color: white;
}
</style>

<p class="sightings-box">
<a href="{% url 'sightings:sightings' %}" class="sightings-link">Back to main page</a>
</p>

<div class="page-header">
<h1>Some Cool Stats!</h1>
</br>
</div>

<div class="content container">

<table style="width:50%">
	<caption># of Sightings per Shift</caption>
		<tr>
			<th>Shift</th>
			<th># of Sightings</th>
		</tr>
			<tr>
				<td> PM </td>
				<td>{{ all_sightings_PM }}</td>
			</tr>
			<tr>
				<td> AM </td>
                                <td>{{ all_sightings_AM }}</td>	
			</tr>
</table>
</br>
<table style=“width:50%”>
	<caption># of Sightings per Fur Color</caption>
		<tr>
			<th>Fur Color</th>
			<th># of Sightings</th>
		</tr>
			<tr>
				<td> Grey </td> 
				<td>{{ all_sightings_grey }}</td>
			</tr>
			<tr>
                                <td> Cinnamon </td>
                                <td>{{ all_sightings_cinnamon }}</td>
                        </tr>
			<tr>
                                <td> Black </td>
                                <td>{{ all_sightings_black }}</td>
                        </tr>
</table>
</br>
<table style=“width:50%”>
	<caption># of Sightings per Activity</caption>
		<tr>
			<th>Running</th>
			<th># of Sightings</th>
		</tr>
			<tr>
				<td> Running </td>
				<td>{{ all_sightings_running }}</td>
			</tr>
</table>
</br>
<table style=“width:50%”>
	<caption># of Sightings per Location</caption>
		<tr>
			<th>Location</th>
			<th># of Sightings</th>
		</tr>
			<tr>
				<td> Ground Plane </td>
				<td>{{ all_sightings_ground_plane }}</td>
			</tr>
			<tr>
                                <td> Above Ground </td>
                                <td>{{ all_sightings_above_ground }}</td>
                        </tr>
</table>
</br>
<table style=“width:50%”>
	<caption># of old and young</caption>
		<tr>
			<th>Age</th>
			<th># of Sightings</th>
		</tr>
			<tr>
				<td> Adult </td> 
				<td>{{ all_sightings_adult }}</td>
			</tr>
			<tr>
                                <td> Juvenile </td>
                                <td>{{ all_sightings_juvenile }}</td>
                        </tr>
</table>
</div>
</html>

squirrels/sightings/templates/sightings/update.html
<!doctype html>
<html>
<p class="sightings-box">
<a href="{% url 'sightings:sightings' %}" class="sightings-link">Back to main page</a>
</p>

<div class="page-header">
<h1>Edit Sighting! </h1>
</br>
</br>
<h2>Squirrel ID: {{squirrel_instance.unique_squirrel_id}}</h2>
</div>

<div class="content container">
{% if error %}<p><strong>{{ error }}</strong></p>{% endif %}

<body>
<form method="POST" class="form">
{% csrf_token %}
	{% for field in form %}
		<div class="fieldWrapper">
			{{field.label_tag}} {{field}}
		</div>
	{% endfor %}
	<button type="submit" class="save btn btn-default">Update Sighting!</button>
	<button type="submit" class="save btn btn-default">Delete Sighting!</button>
{% if success %}<p><strong>{{ success }}</strong></p>{% endif %}
</form>
<a href="{% url 'sightings:delete' squirrel_instance.unique_squirrel_id %}">Delete Sighting!</a>

</body>
</div>
</html>